apiVersion: apps/v1
kind: Deployment
metadata:
  name: subzero-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subzero
  template:
    metadata:
      labels:
        app: subzero
    spec:
      containers:
      - name: subzero
        image: aamir017/subzero:latest  
        ports:
        - containerPort: 5000
